// <auto-generated />
using System;
using APIDeliveryCRM.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIDeliveryCRM.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20251201140437_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfiles", b =>
                {
                    b.Property<int>("ID_ClientProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ClientProfile"));

                    b.Property<string>("Default_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Preferred_payment_method_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ClientProfile");

                    b.HasIndex("Preferred_payment_method_id");

                    b.HasIndex("User_id");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfiles", b =>
                {
                    b.Property<int>("ID_CourierProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierProfile"));

                    b.Property<int>("CurrentStatus_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Current_lat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Current_lon")
                        .HasColumnType("numeric");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_online")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Passport_data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("Total_deliveries")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType_id")
                        .HasColumnType("integer");

                    b.Property<int>("WorkSchedule_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_CourierProfile");

                    b.HasIndex("CurrentStatus_id");

                    b.HasIndex("User_id");

                    b.HasIndex("VehicleType_id");

                    b.HasIndex("WorkSchedule_id");

                    b.ToTable("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_shifts", b =>
                {
                    b.Property<int>("ID_Shift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Shift"));

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ShiftStatus_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_Shift");

                    b.HasIndex("Courier_id");

                    b.HasIndex("ShiftStatus_id");

                    b.ToTable("Courier_Shifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_statuses", b =>
                {
                    b.Property<int>("ID_CourierStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_CourierStatus");

                    b.ToTable("Courier_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Logins", b =>
                {
                    b.Property<int>("ID_Login")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Login"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ID_User")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ID_Login");

                    b.HasIndex("ID_User");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.Property<int>("ID_Notification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Notification"));

                    b.Property<bool>("Is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order_id")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Sent_at")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type_id")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Notification");

                    b.HasIndex("Order_id");

                    b.HasIndex("Type_id");

                    b.HasIndex("User_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification_type", b =>
                {
                    b.Property<int>("ID_NotificationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_NotificationType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_NotificationType");

                    b.ToTable("Notification_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.Property<int>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Order"));

                    b.Property<int>("Client_id")
                        .HasColumnType("integer");

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Delivered_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Final_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_paid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderType_id")
                        .HasColumnType("integer");

                    b.Property<int>("Order_Number")
                        .HasColumnType("integer");

                    b.Property<int?>("Order_StatusesID_OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PackageType_id")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethod_id")
                        .HasColumnType("integer");

                    b.Property<int>("Status_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("Client_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("OrderType_id");

                    b.HasIndex("Order_StatusesID_OrderStatus");

                    b.HasIndex("PackageType_id");

                    b.HasIndex("PaymentMethod_id");

                    b.HasIndex("Status_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Statuses", b =>
                {
                    b.Property<int>("ID_OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_OrderStatus");

                    b.ToTable("Order_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Type", b =>
                {
                    b.Property<int>("ID_OrderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderType"));

                    b.Property<decimal>("Base_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_delivery_factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price_km")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderType");

                    b.ToTable("Order_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Package_Types", b =>
                {
                    b.Property<int>("ID_PackageType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PackageType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Max_height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_wight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PackageType");

                    b.ToTable("Package_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Payment_method", b =>
                {
                    b.Property<int>("ID_PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PaymentMethod"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PaymentMethod");

                    b.ToTable("Payment_Methods");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.Property<int>("ID_Review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Review"));

                    b.Property<int>("Author_id")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUser_id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Review");

                    b.HasIndex("Author_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("TargetUser_id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Role", b =>
                {
                    b.Property<int>("ID_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Schedule_type", b =>
                {
                    b.Property<int>("ID_SheduleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_SheduleType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_SheduleType");

                    b.ToTable("Schedule_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_Status", b =>
                {
                    b.Property<int>("ID_ShiftStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ShiftStatus");

                    b.ToTable("Shift_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_assignments", b =>
                {
                    b.Property<int>("ID_ShiftAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftAssignment"));

                    b.Property<int>("Assignment_sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ShiftAssignment");

                    b.HasIndex("Order_id");

                    b.HasIndex("Shift_id");

                    b.ToTable("Shift_Assignments");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_User"));

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronumic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_User");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Vehicle_types", b =>
                {
                    b.Property<int>("ID_VehicleTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_VehicleTypes"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Max_Weight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Speed_factor")
                        .HasColumnType("numeric");

                    b.HasKey("ID_VehicleTypes");

                    b.ToTable("Vehicle_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfiles", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Payment_method", "Payment_Method")
                        .WithMany()
                        .HasForeignKey("Preferred_payment_method_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment_Method");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfiles", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Courier_statuses", "Courier_statuses")
                        .WithMany("CourierProfiles")
                        .HasForeignKey("CurrentStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Vehicle_types", "Vehicle_Types")
                        .WithMany()
                        .HasForeignKey("VehicleType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Schedule_type", "Schedule_Type")
                        .WithMany()
                        .HasForeignKey("WorkSchedule_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier_statuses");

                    b.Navigation("Schedule_Type");

                    b.Navigation("User");

                    b.Navigation("Vehicle_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_shifts", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.CourierProfiles", "CourierProfiles")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Shift_Status", "Shift_Status")
                        .WithMany("Courier_Shifts")
                        .HasForeignKey("ShiftStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourierProfiles");

                    b.Navigation("Shift_Status");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Logins", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Notification_type", "Notification_Type")
                        .WithMany()
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification_Type");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ClientProfiles", "ClientProfiles")
                        .WithMany()
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfiles", "CourierProfiles")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Type", "Order_Type")
                        .WithMany()
                        .HasForeignKey("OrderType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Statuses", null)
                        .WithMany("Orders")
                        .HasForeignKey("Order_StatusesID_OrderStatus");

                    b.HasOne("APIDeliveryCRM.Model.Package_Types", "PackageType_types")
                        .WithMany()
                        .HasForeignKey("PackageType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Payment_method", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethod_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Statuses", "Status_statuses")
                        .WithMany()
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfiles");

                    b.Navigation("CourierProfiles");

                    b.Navigation("Order_Type");

                    b.Navigation("PackageType_types");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Status_statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "UserAuthor")
                        .WithMany()
                        .HasForeignKey("Author_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "UserTarget")
                        .WithMany()
                        .HasForeignKey("TargetUser_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("UserAuthor");

                    b.Navigation("UserTarget");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_assignments", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Courier_shifts", "Shift")
                        .WithMany()
                        .HasForeignKey("Shift_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_statuses", b =>
                {
                    b.Navigation("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Statuses", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_Status", b =>
                {
                    b.Navigation("Courier_Shifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
