// <auto-generated />
using System;
using APIDeliveryCRM.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIDeliveryCRM.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20251209101923_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.Property<int>("ID_Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Address"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Flat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Address");

                    b.HasIndex("User_id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatMessage", b =>
                {
                    b.Property<int>("ID_ChatMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatMessage"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ChatRoom_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Edited_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("Sender_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_ChatMessage");

                    b.HasIndex("ChatRoom_id");

                    b.HasIndex("Sender_id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatParticipant", b =>
                {
                    b.Property<int>("ID_ChatParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatParticipant"));

                    b.Property<int>("ChatRoom_id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRead_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Left_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ChatParticipant");

                    b.HasIndex("ChatRoom_id");

                    b.HasIndex("User_id");

                    b.ToTable("ChatParticipants");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.Property<int>("ID_ChatRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatRoom"));

                    b.Property<int>("ChatRoomType_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessage_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Order_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ChatRoom");

                    b.HasIndex("ChatRoomType_id");

                    b.HasIndex("Order_id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoomType", b =>
                {
                    b.Property<int>("ID_ChatRoomType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatRoomType"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ChatRoomType");

                    b.ToTable("ChatRoomTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfiles", b =>
                {
                    b.Property<int>("ID_ClientProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ClientProfile"));

                    b.Property<string>("Default_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Preferred_payment_method_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ClientProfile");

                    b.HasIndex("Preferred_payment_method_id");

                    b.HasIndex("User_id");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfiles", b =>
                {
                    b.Property<int>("ID_CourierProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierProfile"));

                    b.Property<int>("CurrentStatus_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Current_lat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Current_lon")
                        .HasColumnType("numeric");

                    b.Property<string>("DriverLicense")
                        .HasColumnType("text");

                    b.Property<bool>("Is_online")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Passport_data")
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("Total_deliveries")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType_id")
                        .HasColumnType("integer");

                    b.Property<int?>("Vehicle_typesID_VehicleTypes")
                        .HasColumnType("integer");

                    b.Property<int>("WorkSchedule_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_CourierProfile");

                    b.HasIndex("CurrentStatus_id");

                    b.HasIndex("User_id");

                    b.HasIndex("VehicleType_id");

                    b.HasIndex("Vehicle_typesID_VehicleTypes");

                    b.HasIndex("WorkSchedule_id");

                    b.ToTable("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_shifts", b =>
                {
                    b.Property<int>("ID_Shift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Shift"));

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ShiftStatus_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_Shift");

                    b.HasIndex("Courier_id");

                    b.HasIndex("ShiftStatus_id");

                    b.ToTable("Courier_Shifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_statuses", b =>
                {
                    b.Property<int>("ID_CourierStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_CourierStatus");

                    b.ToTable("Courier_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Logins", b =>
                {
                    b.Property<int>("ID_Login")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Login"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ID_User")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ID_Login");

                    b.HasIndex("ID_User");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ManagerProfile", b =>
                {
                    b.Property<int>("ID_ManagerProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ManagerProfile"));

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ManagerProfile");

                    b.HasIndex("User_id");

                    b.ToTable("ManagerProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.Property<int>("ID_Notification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Notification"));

                    b.Property<bool>("Is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order_id")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Sent_at")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type_id")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Notification");

                    b.HasIndex("Order_id");

                    b.HasIndex("Type_id");

                    b.HasIndex("User_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification_type", b =>
                {
                    b.Property<int>("ID_NotificationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_NotificationType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_NotificationType");

                    b.ToTable("Notification_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.Property<int>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Order"));

                    b.Property<int>("Client_id")
                        .HasColumnType("integer");

                    b.Property<int?>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAddress_id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Final_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_paid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderType_id")
                        .HasColumnType("integer");

                    b.Property<int>("Order_Number")
                        .HasColumnType("integer");

                    b.Property<int?>("Order_StatusesID_OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PackageType_id")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethod_id")
                        .HasColumnType("integer");

                    b.Property<int>("PickupAddress_id")
                        .HasColumnType("integer");

                    b.Property<int>("Status_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("Client_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("DeliveryAddress_id");

                    b.HasIndex("OrderType_id");

                    b.HasIndex("Order_StatusesID_OrderStatus");

                    b.HasIndex("PackageType_id");

                    b.HasIndex("PaymentMethod_id");

                    b.HasIndex("PickupAddress_id");

                    b.HasIndex("Status_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Statuses", b =>
                {
                    b.Property<int>("ID_OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderStatus"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_OrderStatus");

                    b.ToTable("Order_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Type", b =>
                {
                    b.Property<int>("ID_OrderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderType"));

                    b.Property<decimal>("Base_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_delivery_factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price_km")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderType");

                    b.ToTable("Order_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Package_Types", b =>
                {
                    b.Property<int>("ID_PackageType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PackageType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Max_height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_wight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PackageType");

                    b.ToTable("Package_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Payment_method", b =>
                {
                    b.Property<int>("ID_PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PaymentMethod"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PaymentMethod");

                    b.ToTable("Payment_Methods");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.Property<int>("ID_Review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Review"));

                    b.Property<int>("Author_id")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUser_id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Review");

                    b.HasIndex("Author_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("TargetUser_id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Role", b =>
                {
                    b.Property<int>("ID_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Schedule_type", b =>
                {
                    b.Property<int>("ID_SheduleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_SheduleType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_SheduleType");

                    b.ToTable("Schedule_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_Status", b =>
                {
                    b.Property<int>("ID_ShiftStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ShiftStatus");

                    b.ToTable("Shift_Statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_assignments", b =>
                {
                    b.Property<int>("ID_ShiftAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftAssignment"));

                    b.Property<int>("Assignment_sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ShiftAssignment");

                    b.HasIndex("Order_id");

                    b.HasIndex("Shift_id");

                    b.ToTable("Shift_Assignments");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_User"));

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronumic")
                        .HasColumnType("text");

                    b.Property<int>("Role_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_User");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Vehicle_types", b =>
                {
                    b.Property<int>("ID_VehicleTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_VehicleTypes"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Max_Weight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Speed_factor")
                        .HasColumnType("numeric");

                    b.HasKey("ID_VehicleTypes");

                    b.ToTable("Vehicle_types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatMessage", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoom_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatParticipant", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoom", "ChatRoom")
                        .WithMany("Participants")
                        .HasForeignKey("ChatRoom_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoomType", "ChatRoomType")
                        .WithMany("ChatRooms")
                        .HasForeignKey("ChatRoomType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany("ChatRooms")
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChatRoomType");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfiles", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Payment_method", "Payment_Method")
                        .WithMany()
                        .HasForeignKey("Preferred_payment_method_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment_Method");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfiles", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Courier_statuses", "Courier_statuses")
                        .WithMany("CourierProfiles")
                        .HasForeignKey("CurrentStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Vehicle_types", "Vehicle_Types")
                        .WithMany()
                        .HasForeignKey("VehicleType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Vehicle_types", null)
                        .WithMany("CourierProfiles")
                        .HasForeignKey("Vehicle_typesID_VehicleTypes");

                    b.HasOne("APIDeliveryCRM.Model.Schedule_type", "Schedule_Type")
                        .WithMany()
                        .HasForeignKey("WorkSchedule_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier_statuses");

                    b.Navigation("Schedule_Type");

                    b.Navigation("User");

                    b.Navigation("Vehicle_Types");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_shifts", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.CourierProfiles", "CourierProfiles")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Shift_Status", "Shift_Status")
                        .WithMany("Courier_Shifts")
                        .HasForeignKey("ShiftStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourierProfiles");

                    b.Navigation("Shift_Status");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Logins", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ManagerProfile", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Notification_type", "Notification_Type")
                        .WithMany()
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification_Type");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ClientProfiles", "ClientProfiles")
                        .WithMany()
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfiles", "CourierProfiles")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("APIDeliveryCRM.Model.Address", "DeliveryAddress")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DeliveryAddress_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Type", "Order_Type")
                        .WithMany()
                        .HasForeignKey("OrderType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Statuses", null)
                        .WithMany("Orders")
                        .HasForeignKey("Order_StatusesID_OrderStatus");

                    b.HasOne("APIDeliveryCRM.Model.Package_Types", "PackageType_types")
                        .WithMany()
                        .HasForeignKey("PackageType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Payment_method", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethod_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Address", "PickupAddress")
                        .WithMany("PickupOrders")
                        .HasForeignKey("PickupAddress_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order_Statuses", "Status_statuses")
                        .WithMany()
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfiles");

                    b.Navigation("CourierProfiles");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Order_Type");

                    b.Navigation("PackageType_types");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PickupAddress");

                    b.Navigation("Status_statuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "UserAuthor")
                        .WithMany()
                        .HasForeignKey("Author_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "UserTarget")
                        .WithMany()
                        .HasForeignKey("TargetUser_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("UserAuthor");

                    b.Navigation("UserTarget");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_assignments", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Courier_shifts", "Shift")
                        .WithMany()
                        .HasForeignKey("Shift_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.Navigation("DeliveryOrders");

                    b.Navigation("PickupOrders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoomType", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Courier_statuses", b =>
                {
                    b.Navigation("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order_Statuses", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Shift_Status", b =>
                {
                    b.Navigation("Courier_Shifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ChatParticipants");

                    b.Navigation("Logins");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Vehicle_types", b =>
                {
                    b.Navigation("CourierProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
