// <auto-generated />
using System;
using APIDeliveryCRM.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIDeliveryCRM.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20260109165600_Profiles edited")]
    partial class Profilesedited
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.Property<int>("ID_Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Address"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<string>("Flat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Address");

                    b.HasIndex("Company_id");

                    b.HasIndex("User_id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.AuditLog", b =>
                {
                    b.Property<int>("ID_AuditLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_AuditLog"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_AuditLog");

                    b.HasIndex("Company_id");

                    b.HasIndex("User_id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatMessage", b =>
                {
                    b.Property<int>("ID_ChatMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatMessage"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ChatRoom_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Edited_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("Sender_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_ChatMessage");

                    b.HasIndex("ChatRoom_id");

                    b.HasIndex("Sender_id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatParticipant", b =>
                {
                    b.Property<int>("ID_ChatParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatParticipant"));

                    b.Property<int>("ChatRoom_id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRead_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Left_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ChatParticipant");

                    b.HasIndex("ChatRoom_id");

                    b.HasIndex("User_id");

                    b.ToTable("ChatParticipants");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.Property<int>("ID_ChatRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatRoom"));

                    b.Property<int>("ChatRoomType_id")
                        .HasColumnType("integer");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessage_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Order_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ChatRoom");

                    b.HasIndex("ChatRoomType_id");

                    b.HasIndex("Company_id");

                    b.HasIndex("Order_id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoomType", b =>
                {
                    b.Property<int>("ID_ChatRoomType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ChatRoomType"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ChatRoomType");

                    b.ToTable("ChatRoomTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfile", b =>
                {
                    b.Property<int>("ID_ClientProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ClientProfile"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<string>("Default_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Preferred_payment_method_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ClientProfile");

                    b.HasIndex("Company_id");

                    b.HasIndex("Preferred_payment_method_id");

                    b.HasIndex("User_id");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Company", b =>
                {
                    b.Property<int>("ID_Company")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Company"));

                    b.Property<string>("AzureStorageConnectionString")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AzureStorageContainerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("KafkaBootstrapServers")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KafkaGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxOrdersPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subdomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_Company");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierFuelCard", b =>
                {
                    b.Property<int>("ID_CF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CF"));

                    b.Property<int>("AssignedByUser_id")
                        .HasColumnType("integer");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<int>("FuelCard_id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_backup")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_primary")
                        .HasColumnType("boolean");

                    b.HasKey("ID_CF");

                    b.HasIndex("AssignedByUser_id");

                    b.HasIndex("Company_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("FuelCard_id");

                    b.ToTable("CourierFuelCards");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfile", b =>
                {
                    b.Property<int>("ID_CourierProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierProfile"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStatus_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Current_lat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Current_lon")
                        .HasColumnType("numeric");

                    b.Property<string>("DriverLicense")
                        .HasColumnType("text");

                    b.Property<bool>("Is_online")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Passport_data")
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("Total_deliveries")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleCategory_id")
                        .HasColumnType("integer");

                    b.Property<int>("WorkSchedule_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_CourierProfile");

                    b.HasIndex("Company_id");

                    b.HasIndex("CurrentStatus_id");

                    b.HasIndex("User_id");

                    b.HasIndex("VehicleCategory_id");

                    b.HasIndex("WorkSchedule_id");

                    b.ToTable("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierShift", b =>
                {
                    b.Property<int>("ID_Shift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Shift"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ShiftStatus_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_Shift");

                    b.HasIndex("Company_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("ShiftStatus_id");

                    b.ToTable("CourierShifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierStatus", b =>
                {
                    b.Property<int>("ID_CourierStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_CourierStatus"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_CourierStatus");

                    b.ToTable("CourierStatuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelCard", b =>
                {
                    b.Property<int>("ID_Card")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Card"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("FuelCompany_id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("NumberCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Odometer")
                        .HasColumnType("boolean");

                    b.Property<int>("PIN")
                        .HasColumnType("integer");

                    b.Property<int>("Status_id")
                        .HasColumnType("integer");

                    b.Property<int>("Type_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Card");

                    b.HasIndex("Company_id");

                    b.HasIndex("FuelCompany_id");

                    b.HasIndex("Status_id");

                    b.HasIndex("Type_id");

                    b.ToTable("FuelCards");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelCardStatus", b =>
                {
                    b.Property<int>("ID_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Status"));

                    b.Property<bool>("IsCanBeUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Status");

                    b.ToTable("FuelCardStatuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelCardType", b =>
                {
                    b.Property<int>("ID_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Type"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Type");

                    b.ToTable("FuelCardTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelCompany", b =>
                {
                    b.Property<int>("ID_Company")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Company"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Company");

                    b.ToTable("FuelCompanies");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelType", b =>
                {
                    b.Property<int>("ID_FuelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_FuelType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_FuelType");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Login", b =>
                {
                    b.Property<int>("ID_Login")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Login"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ID_User")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ID_Login");

                    b.HasIndex("ID_User");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ManagerProfile", b =>
                {
                    b.Property<int>("ID_ManagerProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ManagerProfile"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Passport_issued_by")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Passport_issued_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Passport_number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Passport_series")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ManagerProfile");

                    b.HasIndex("Company_id");

                    b.HasIndex("User_id");

                    b.ToTable("ManagerProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.Property<int>("ID_Notification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Notification"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order_id")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Sent_at")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type_id")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Notification");

                    b.HasIndex("Company_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Type_id");

                    b.HasIndex("User_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.NotificationType", b =>
                {
                    b.Property<int>("ID_NotificationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_NotificationType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_NotificationType");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.Property<int>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Order"));

                    b.Property<int>("Client_id")
                        .HasColumnType("integer");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int?>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAddress_id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Final_cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_paid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderStatusID_OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderType_id")
                        .HasColumnType("integer");

                    b.Property<int>("Order_Number")
                        .HasColumnType("integer");

                    b.Property<int>("PackageType_id")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethod_id")
                        .HasColumnType("integer");

                    b.Property<int>("PickupAddress_id")
                        .HasColumnType("integer");

                    b.Property<int>("Status_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("Client_id");

                    b.HasIndex("Company_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("DeliveryAddress_id");

                    b.HasIndex("OrderStatusID_OrderStatus");

                    b.HasIndex("OrderType_id");

                    b.HasIndex("PackageType_id");

                    b.HasIndex("PaymentMethod_id");

                    b.HasIndex("PickupAddress_id");

                    b.HasIndex("Status_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.OrderStatus", b =>
                {
                    b.Property<int>("ID_OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderStatus"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_OrderStatus");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.OrderType", b =>
                {
                    b.Property<int>("ID_OrderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_OrderType"));

                    b.Property<decimal>("Base_price")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Estimated_delivery_factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price_km")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderType");

                    b.ToTable("OrderTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.PackageType", b =>
                {
                    b.Property<int>("ID_PackageType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PackageType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Max_height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max_wight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PackageType");

                    b.ToTable("PackageTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.PaymentMethod", b =>
                {
                    b.Property<int>("ID_PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PaymentMethod"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_PaymentMethod");

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Report", b =>
                {
                    b.Property<int>("ID_Report")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Report"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status_id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_Report");

                    b.HasIndex("Company_id");

                    b.HasIndex("Status_id");

                    b.HasIndex("User_id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ReportStatus", b =>
                {
                    b.Property<int>("ID_ReportStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ReportStatus"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ReportStatus");

                    b.ToTable("ReportStatuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.Property<int>("ID_Review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Review"));

                    b.Property<int>("Author_id")
                        .HasColumnType("integer");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("TargetUser_id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Review");

                    b.HasIndex("Author_id");

                    b.HasIndex("Company_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("TargetUser_id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Role", b =>
                {
                    b.Property<int>("ID_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ScheduleType", b =>
                {
                    b.Property<int>("ID_SheduleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_SheduleType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_SheduleType");

                    b.ToTable("ScheduleTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ShiftAssignment", b =>
                {
                    b.Property<int>("ID_ShiftAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftAssignment"));

                    b.Property<int>("Assignment_sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("Order_id")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_id")
                        .HasColumnType("integer");

                    b.HasKey("ID_ShiftAssignment");

                    b.HasIndex("Company_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Shift_id");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ShiftStatus", b =>
                {
                    b.Property<int>("ID_ShiftStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_ShiftStatus"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID_ShiftStatus");

                    b.ToTable("ShiftStatuses");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.TransmissionType", b =>
                {
                    b.Property<int>("ID_TransmisType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_TransmisType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_TransmisType");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_User"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronumic")
                        .HasColumnType("text");

                    b.Property<int>("Role_id")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_User");

                    b.HasIndex("Company_id");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Vehicle", b =>
                {
                    b.Property<int>("ID_Vehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Vehicle"));

                    b.Property<int>("BodyType_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cargo_volume")
                        .HasColumnType("numeric");

                    b.Property<int>("Category_id")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCourier_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Current_mileage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FuelTank_Capacity")
                        .HasColumnType("numeric");

                    b.Property<int>("FuelType_id")
                        .HasColumnType("integer");

                    b.Property<string>("Insurance_policy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("License_plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Max_cargo_weight")
                        .HasColumnType("numeric");

                    b.Property<int>("Model_id")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("date");

                    b.HasKey("ID_Vehicle");

                    b.HasIndex("BodyType_id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Company_id");

                    b.HasIndex("CurrentCourier_id");

                    b.HasIndex("FuelType_id");

                    b.HasIndex("Model_id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleAssignment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Company_id")
                        .HasColumnType("integer");

                    b.Property<int>("Courier_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mileage_end")
                        .HasColumnType("integer");

                    b.Property<int>("Mileage_start")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vehicle_id")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Company_id");

                    b.HasIndex("Courier_id");

                    b.HasIndex("Vehicle_id");

                    b.ToTable("VehicleAssignments");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleBodyType", b =>
                {
                    b.Property<int>("ID_BodyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_BodyType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_BodyType");

                    b.ToTable("VehicleBodyTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleBrand", b =>
                {
                    b.Property<int>("ID_Brand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Brand"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Brand");

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleCategory", b =>
                {
                    b.Property<int>("ID_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Category"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Max_Weight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Speed_factor")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Category");

                    b.ToTable("VehicleCategories");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleDriveType", b =>
                {
                    b.Property<int>("ID_DriveType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_DriveType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_DriveType");

                    b.ToTable("DriveTypes");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleModel", b =>
                {
                    b.Property<int>("ID_Model")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Model"));

                    b.Property<decimal>("AvgFuelCity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AvgFuelHighWay")
                        .HasColumnType("numeric");

                    b.Property<int>("Brand_id")
                        .HasColumnType("integer");

                    b.Property<int>("DriveType_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("EngineCapacity")
                        .HasColumnType("numeric");

                    b.Property<int>("HorsePower")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransmissionType_id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("date");

                    b.HasKey("ID_Model");

                    b.HasIndex("Brand_id");

                    b.HasIndex("DriveType_id");

                    b.HasIndex("TransmissionType_id");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.AuditLog", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatMessage", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoom_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatParticipant", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoom", "ChatRoom")
                        .WithMany("Participants")
                        .HasForeignKey("ChatRoom_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ChatRoomType", "ChatRoomType")
                        .WithMany("ChatRooms")
                        .HasForeignKey("ChatRoomType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany("ChatRooms")
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChatRoomType");

                    b.Navigation("Company");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ClientProfile", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("Preferred_payment_method_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierFuelCard", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("AssignedByUser_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfile", "CourierProfile")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.FuelCard", "FuelCard")
                        .WithMany()
                        .HasForeignKey("FuelCard_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CourierProfile");

                    b.Navigation("FuelCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierProfile", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierStatus", "CourierStatus")
                        .WithMany("CourierProfiles")
                        .HasForeignKey("CurrentStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.VehicleCategory", "VehicleCategory")
                        .WithMany("CourierProfiles")
                        .HasForeignKey("VehicleCategory_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.ScheduleType", "ScheduleType")
                        .WithMany()
                        .HasForeignKey("WorkSchedule_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CourierStatus");

                    b.Navigation("ScheduleType");

                    b.Navigation("User");

                    b.Navigation("VehicleCategory");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierShift", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfile", "CourierProfile")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.ShiftStatus", "ShiftStatus")
                        .WithMany("CourierShifts")
                        .HasForeignKey("ShiftStatus_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CourierProfile");

                    b.Navigation("ShiftStatus");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.FuelCard", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.FuelCompany", "FuelCompany")
                        .WithMany()
                        .HasForeignKey("FuelCompany_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.FuelCardStatus", "FuelCardStatus")
                        .WithMany()
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.FuelCardType", "FuelCardType")
                        .WithMany()
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("FuelCardStatus");

                    b.Navigation("FuelCardType");

                    b.Navigation("FuelCompany");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Login", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ManagerProfile", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Notification", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("NotificationType");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfile", "CourierProfile")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("APIDeliveryCRM.Model.Address", "DeliveryAddress")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DeliveryAddress_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.OrderStatus", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusID_OrderStatus");

                    b.HasOne("APIDeliveryCRM.Model.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.PackageType", "PackageType")
                        .WithMany()
                        .HasForeignKey("PackageType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethod_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Address", "PickupAddress")
                        .WithMany("PickupOrders")
                        .HasForeignKey("PickupAddress_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("Company");

                    b.Navigation("CourierProfile");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");

                    b.Navigation("PackageType");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PickupAddress");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Report", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.ReportStatus", "ReportStatus")
                        .WithMany("Reports")
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ReportStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Review", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.User", "UserAuthor")
                        .WithMany()
                        .HasForeignKey("Author_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.User", "UserTarget")
                        .WithMany()
                        .HasForeignKey("TargetUser_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Order");

                    b.Navigation("UserAuthor");

                    b.Navigation("UserTarget");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ShiftAssignment", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierShift", "Shift")
                        .WithMany()
                        .HasForeignKey("Shift_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Order");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Vehicle", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.VehicleBodyType", "VehicleBodyType")
                        .WithMany()
                        .HasForeignKey("BodyType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.VehicleCategory", "VehicleCategory")
                        .WithMany()
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfile", "CourierProfile")
                        .WithMany()
                        .HasForeignKey("CurrentCourier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("Model_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CourierProfile");

                    b.Navigation("FuelType");

                    b.Navigation("VehicleBodyType");

                    b.Navigation("VehicleCategory");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleAssignment", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.CourierProfile", "Courier")
                        .WithMany()
                        .HasForeignKey("Courier_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Courier");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleModel", b =>
                {
                    b.HasOne("APIDeliveryCRM.Model.VehicleBrand", "VehicleBrand")
                        .WithMany()
                        .HasForeignKey("Brand_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.VehicleDriveType", "VehicleDriveType")
                        .WithMany()
                        .HasForeignKey("DriveType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIDeliveryCRM.Model.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleDriveType");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Address", b =>
                {
                    b.Navigation("DeliveryOrders");

                    b.Navigation("PickupOrders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ChatRoomType", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.CourierStatus", b =>
                {
                    b.Navigation("CourierProfiles");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.Order", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ReportStatus", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.ShiftStatus", b =>
                {
                    b.Navigation("CourierShifts");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ChatParticipants");

                    b.Navigation("Logins");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("APIDeliveryCRM.Model.VehicleCategory", b =>
                {
                    b.Navigation("CourierProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
