using System.IO;
using APIDeliveryCRM.Responses;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace APIDeliveryCRM.Services;

internal static class FinanceReportPdfBuilder
{
    public static byte[] Build(FinanceDashboardResponse d)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(24);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text("Finance Report").FontSize(18).SemiBold();
                    col.Item().Text($"Period (UTC): {d.PeriodFromUtc:yyyy-MM-dd HH:mm} - {d.PeriodToUtc:yyyy-MM-dd HH:mm}").FontColor(Colors.Grey.Darken2);
                });

                page.Content().Column(col =>
                {
                    col.Spacing(6);
                    col.Item().Text($"Orders created: {d.OrdersCreatedInPeriod}");
                    col.Item().Text($"Revenue delivered: {d.RevenueDeliveredInPeriod:N0}");
                    col.Item().Text($"On-time: {d.OnTimePercent:0.0}%");
                    col.Item().Text($"Late: {d.LatePercent:0.0}%");
                    col.Item().Text($"Avg delivery hours: {d.AvgDeliveryHours:0.0}");
                    col.Item().Text($"Fuel consumed (est.): {d.EstimatedFuelUsedLiters:0.0} L");
                    col.Item().Text($"Fuel saved (est.): {d.EstimatedFuelSavedLiters:0.0} L ({d.EstimatedFuelSavingsPercent:0.0}%)");
                    col.Item().Text($"Fuel model: {d.FuelConsumptionLitersPer100Km:0.0} L/100km").FontColor(Colors.Grey.Darken2);
                });

                page.Footer().AlignRight().Text(x =>
                {
                    x.Span("Generated by DeliveryCRM");
                    x.Span(" | ");
                    x.CurrentPageNumber();
                });
            });
        });

        return doc.GeneratePdf();
    }
}
